### ISSUE TITLE
Serendipitous benchmark

### ISSUE THREAD

**Issue by flagello** [WebReflection/basicHTML#2]
I happened to start looking for a leaner DOM implementation for Node just around the time of your first commit. [Here's the benchmark I put together.](https://github.com/flagello/node-dom-benchmarks)

**Comment by WebReflection** [comment]
Awesome! However, while it's encouraging to know basicHTML wins 2 out of 4 and it's competitive in remaining 2, I haven't even thought about performance yet and the usage of `forEach` instead of usually faster for loops is all over the place.

I have different goals right now so I'd say it's a bit early to benchmark here :wink: 

Would you like me to link such benchmark on this README too ?

**Comment by flagello** [comment]
As you wish really — it'll help me understand the tradeoffs in choosing a DOM-like API on the server, so if it can be any help to others I don't see why not. 😄

_(just rewrote it — should be more precise)_

**Comment by WebReflection** [comment]
I've discovered today that NativeScript is not compatible with parse5, which is a dependency of this module.

This is a pity, 'cause parse5 seems to be fast enough and very battle tested but if NativeScript won't solve this issue, and since they changed their angular implementation instead of fixing it in the past, I might need to change parser as well, hence my questions?

  * do you know any other parser that is reasonably fast, lightweight, and HTML compliant?
  * maybe it makes sense to wait for such update before showing benchmark results in here?

Thanks for any eventual help, I'm asking you 'cause you're exploring already these projects.
I'll also have a look at their parsers, hoping these are not all based on parse5.

Best Regards

**Comment by flagello** [comment]
I had already in mind to suggest switching to [htmlparser2](https://github.com/fb55/htmlparser2) or a variant thereof. It's a parse5 built-in!

```js
const {parse, treeAdapters: {htmlparser2: treeAdapter}} = require("parse5")
const html = '<!DOCTYPE html><html><head></head><body>Hi there!</body></html>'
const document = parse(html, {treeAdapter: treeAdapter})
```


While trying to get parse5 to parse [undom](https://github.com/developit/undom/tree/master/src), I discovered [it relies on and allows for custom tree adapters](http://inikulin.github.io/parse5/interfaces/options.parseroptions.html#treeadapter). I ended up patching the default tree adapter to make it trivially support undom. Considering [their](https://github.com/inikulin/parse5/blob/master/lib/tree_adapters/default.js) [implementations](https://github.com/inikulin/parse5/blob/master/lib/tree_adapters/htmlparser2.js), even if htmlparser2 doesn't work with NativeScript, implementing a purpose-built tree adapter shouldn't be too much work.

**Comment by WebReflection** [comment]
uhm ... I actually just need something compatible with XML too ... a simple <node attr>content</node> with eventually <void-node attr/> capability ... I think I'll end up writing a stupid one myself or NativeScript, which was the initial reason I even created this repository, won't be happy :cry: 

thanks for the hint though, I'll have a better look soon

**Comment by flagello** [comment]
htmlparser2 is indeed XML compatible. Haven't used it directly for that purpose, but you could try to look into using it without parse5.

**Comment by WebReflection** [comment]
I've just published `v0.4.0` which drops `parse5` in favor of `htmlparser2`.

I'd like to know if you could countr-verify the benchmark and tell me if this was an improvement, a regression, or an "_it's OK anyway_" change.

NativeScript seems to be fine with htmlparser2 though, so I hope it won't be a regression

**Comment by flagello** [comment]
https://github.com/flagello/node-dom-benchmarks/commit/f55fd1501596d67b9140a6a71d5397ec4646522e

Better in  `parse-cached` and `serialize-cached` — others slightly better or more or less the same. Should be great given NativeScript support!

**Comment by WebReflection** [comment]
I'm not sure I understand that benchmark .... but thanks!

**Comment by flagello** [comment]
I'm all ears! 

The tests are pretty barebones for the time being, and I've refactored it twice with Benchmark.js because `Benchmark.suite` does not have `setup` and `teardown` which I thought would result in a more accurate and modular approach.

I'd be very interested in improvements and suggestions. `endom` and `html-element` do not use a parser for the innerHTML setter (`parse` and `parse-cached` are skewed), and I'm considering extending `endom` with one, if it makes sense for the specific use-case I'm exploring.

**Comment by WebReflection** [comment]
> endom and html-element do not use a parser for the innerHTML setter

yeah, I've checked them both and `html-element` looked like some sort of a joke compared to others, specially because of these comments:
https://github.com/1N50MN14/html-element/blob/master/index.js#L215-L222

> ... parsing is hard and will need added deps!

I'd like to PR a "_you don't say_" there :laughing: 


Anyway, it looks like `htmlparser2` is even a better choice than `parse5` so thanks for the hint :+1:

**Comment by flagello** [comment]
Haha, I guess he was in a rush. 😛

You're welcome! 👍
